---
name: CGI-Application-Bouquet-Rose
version: 1.00
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: Generate a set of CGI::Application-based classes
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Carp: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  HTML::Template: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  CGI::Application::Bouquet::Rose:
    file: lib/CGI/Application/Bouquet/Rose.pm
    version: 1.00
  CGI::Application::Bouquet::Rose::Config:
    file: lib/CGI/Application/Bouquet/Rose/Config.pm
    version: 1.00
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
